## aliases for the command. your first one is the primary command prefix, used in help messages.
## you may want to add more to act as a drop-in replacement for other `giphy` bots
command_aliases: 
  - gifme
  - gif

## enable fallback to giphy search? must have a giphy api key defined below
allow_fallback: true

## minimum number of database entries required to prevent falling back to giphy search,
## if fallback is enabled
fallback_threshold: 1

giphy_api_key: ""

## allow saving messages in plain-text to the database? security risk for encrypted rooms!
allow_non_files: true

## send a message with every image returned from the database?
## this informs people that the response is already saved and does not need to be saved again
say_already_saved: false

## define a list of users who can save messages to the database?
restrict_users: false

allowed_users:
  - "@user1:server.tld"
  - "@user2:server.tld"
